ValueSet: JDV_J255_SurspecialiteTransversale_RPPS
Id: JDV-J255-SurspecialiteTransversale-RPPS
Description: "Surspécialité (compétence) acquise par l'interne à l'issue d'une Formation Spécialisée Transversale (FST)"
* ^meta.versionId = "3"
* ^meta.lastUpdated = "2025-07-02T17:06:13.158+00:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2023-12-15T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J255-SurspecialiteTransversale-RPPS/FHIR/JDV-J255-SurspecialiteTransversale-RPPS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.282"
* ^version = "20240329120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-03-29T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FR
* $TRE-R359-SurspecialiteTransversale#SST01 "Addictologie"
* $TRE-R359-SurspecialiteTransversale#SST02 "Bio-informatique médicale"
* $TRE-R359-SurspecialiteTransversale#SST03 "Cancérologie déclinaison hémato-cancérologie pédiatrique"
* $TRE-R359-SurspecialiteTransversale#SST04 "Cancérologie traitements médicaux des cancers"
* $TRE-R359-SurspecialiteTransversale#SST05 "Cardiologie pédiatrique et congénitale"
* $TRE-R359-SurspecialiteTransversale#SST06 "Chirurgie de la main"
* $TRE-R359-SurspecialiteTransversale#SST07 "Chirurgie en situation de guerre ou de catastrophe"
* $TRE-R359-SurspecialiteTransversale#SST08 "Chirurgie orbito-palpébro-lacrymale"
* $TRE-R359-SurspecialiteTransversale#SST09 "Douleur"
* $TRE-R359-SurspecialiteTransversale#SST10 "Expertise médicale-préjudice corporel"
* $TRE-R359-SurspecialiteTransversale#SST11 "Foetopathologie"
* $TRE-R359-SurspecialiteTransversale#SST12 "Génétique et médecine moléculaire bioclinique"
* $TRE-R359-SurspecialiteTransversale#SST13 "Hématologie bioclinique"
* $TRE-R359-SurspecialiteTransversale#SST14 "Hygiène-prévention de l'infection, résistances"
* $TRE-R359-SurspecialiteTransversale#SST15 "Maladies allergiques"
* $TRE-R359-SurspecialiteTransversale#SST16 "Médecine hospitalière polyvalente"
* $TRE-R359-SurspecialiteTransversale#SST17 "Médecine palliative"
* $TRE-R359-SurspecialiteTransversale#SST18 "Médecine scolaire"
* $TRE-R359-SurspecialiteTransversale#SST19 "Médecine en situation de guerre ou en SSE"
* $TRE-R359-SurspecialiteTransversale#SST20 "Médecine et biologie de la reproduction-andrologie"
* $TRE-R359-SurspecialiteTransversale#SST21 "Médecine du sport"
* $TRE-R359-SurspecialiteTransversale#SST22 "Nutrition appliquée"
* $TRE-R359-SurspecialiteTransversale#SST23 "Pharmacologie médicale/ thérapeutique"
* $TRE-R359-SurspecialiteTransversale#SST24 "Sommeil"
* $TRE-R359-SurspecialiteTransversale#SST25 "Thérapie cellulaire/ transfusion"
* $TRE-R359-SurspecialiteTransversale#SST26 "Urgences pédiatriques"