ValueSet: JDV_J286_ProfilUtilisateurReferentielNational_ROR
Id: JDV-J286-ProfilUtilisateurReferentielNational-ROR
Description: "Profils utilisateurs du ROR National"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2024-12-19T18:02:42.491+00:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2024-10-25T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J286_ProfilUtilisateurReferentielNational_ROR/FHIR/JDV-J286-ProfilUtilisateurReferentielNational-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.256"
* ^version = "20241213120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-12-13T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* $TRE-R369-ProfilUtilisateurReferentielNational#ADMIN_NAT "Administrateur National"
* $TRE-R369-ProfilUtilisateurReferentielNational#ADMIN_REG "Administrateur Régional"
* $TRE-R369-ProfilUtilisateurReferentielNational#RESP_QA "Responsable Qualité"
* $TRE-R369-ProfilUtilisateurReferentielNational#RESP_OFFRE_STRUCT "Responsable Offre de structure"
* $TRE-R369-ProfilUtilisateurReferentielNational#RESP_DISPO_PLACE "Responsable Disponibilité en lit / place"
* $TRE-R369-ProfilUtilisateurReferentielNational#PORTEUR_OFFRE "Porteur d'offre"
* $TRE-R369-ProfilUtilisateurReferentielNational#PSL "Professionnel de Santé Libéral (PSL)"
* $TRE-R369-ProfilUtilisateurReferentielNational#ADMIN_METIER "Administrateur Métier"
* $TRE-R369-ProfilUtilisateurReferentielNational#SUPPORT "Support"
* $TRE-R369-ProfilUtilisateurReferentielNational#REF_MSP "Référent Maison de Santé Pluriprofessionnelle"