name: DM - Création - Terminologie de référence (TRE)
description: "Nomenclatures des Objets de Santé (NOS) Demande de création d'une terminologie de référence (TRE)."
title: "Creation-TRE_Nom de la nomenclature"
labels: ["Création-TRE"]
body:
  - type: markdown
    attributes:
      value: "# Initialisation"
  - type: input
    id: Demandeur
    attributes:
      label: Système demandeur
    validations:
      required: true
