name: DM - Création/Modification - Nomenclature
description: "Nomenclatures des Objets de Santé (NOS) Demande de création/modification d'une nomenclature."
title: "Création/Modification"
labels: ["Création/Modification"]
body:
  - type: markdown
    attributes:
      value: "# Initialisation"
  - type: input
    id: Demandeur
    attributes:
      label: Système demandeur
    validations:
      required: true
  - type: input
    id: DateGen
    attributes:
      label: Date de génération souhaitée
      placeholder: MM/AAAA
    validations:
      required: true
  - type: textarea
    id: Contexte
    attributes:
      label: Contexte
      description: Veuillez renseigner une description ainsi que le cadre juridique
    validations:
      required: true
