Alias: $terminologie-SERAFINPH = https://smt.esante.gouv.fr/terminologie-SERAFINPH

ValueSet: JDV_J285_Besoins_SERAFIN
Id: JDV-J285-Besoins-SERAFIN
Description: "Liste des besoins provenant de la terminologie SERAFIN"
* ^meta.versionId = "3"
* ^meta.lastUpdated = "2024-10-31T18:01:44.446+00:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2024-10-25T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J285-Besoins_SERAFIN/FHIR/JDV-J285-Besoins-SERAFIN"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.254"
* ^version = "20241025120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-10-25T12:00:00+01:00"
* ^publisher = "ANS"
* ^contact.name = "ANS"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://esante.gouv.fr"
* ^jurisdiction = urn:iso:std:iso:3166#FR "France"
* $terminologie-SERAFINPH#1 "Besoins"
* $terminologie-SERAFINPH#1.1 "Besoins en matière de santé somatique ou psychique"
* $terminologie-SERAFINPH#1.1.1 "Besoins en matière de fonctions mentales, psychiques, cognitives et du système nerveux"
* $terminologie-SERAFINPH#1.1.10 "Besoins pour entretenir et prendre soin de sa santé"
* $terminologie-SERAFINPH#1.1.2 "Besoins en matière de fonctions sensorielles"
* $terminologie-SERAFINPH#1.1.3 "Besoins en matière de douleur"
* $terminologie-SERAFINPH#1.1.4 "Besoins relatifs à la voix, à la parole et à l'appareil bucco-dentaire"
* $terminologie-SERAFINPH#1.1.5 "Besoins en matière de fonctions cardio-vasculaire, hématopoïétique, immunitaire et respiratoire"
* $terminologie-SERAFINPH#1.1.6 "Besoins en matière de fonctions digestive, métabolique et endocrinienne"
* $terminologie-SERAFINPH#1.1.7 "Besoins en matière de fonctions génito-urinaire et reproductive"
* $terminologie-SERAFINPH#1.1.8 "Besoins en matière de fonctions locomotrices"
* $terminologie-SERAFINPH#1.1.9 "Besoins relatifs à la peau et aux structures associées"
* $terminologie-SERAFINPH#1.2 "Besoins en matière d'autonomie"
* $terminologie-SERAFINPH#1.2.1 "Besoins en matière d'autonomie"
* $terminologie-SERAFINPH#1.2.1.1 "Besoins en lien avec l'entretien personnel"
* $terminologie-SERAFINPH#1.2.1.2 "Besoins en lien avec les relations et les interactions avec autrui"
* $terminologie-SERAFINPH#1.2.1.3 "Besoins pour la mobilité"
* $terminologie-SERAFINPH#1.2.1.4 "Besoins pour prendre des décisions adaptées et pour la sécurité"
* $terminologie-SERAFINPH#1.3 "Besoins pour la participation sociale"
* $terminologie-SERAFINPH#1.3.1 "Besoins pour accéder aux droits et à la citoyenneté"
* $terminologie-SERAFINPH#1.3.1.1 "Besoins pour accéder aux droits et à la citoyenneté"
* $terminologie-SERAFINPH#1.3.2 "Besoins pour vivre dans un logement et accomplir les activités domestiques"
* $terminologie-SERAFINPH#1.3.2.1 "Besoins pour vivre dans un logement"
* $terminologie-SERAFINPH#1.3.2.2 "Besoins pour accomplir les activités domestiques"
* $terminologie-SERAFINPH#1.3.3 "Besoins pour l'insertion sociale et professionnelle et pour exercer ses rôles sociaux"
* $terminologie-SERAFINPH#1.3.3.1 "Besoins en lien avec la vie scolaire et étudiante"
* $terminologie-SERAFINPH#1.3.3.2 "Besoins en lien avec le travail et l'emploi"
* $terminologie-SERAFINPH#1.3.3.3 "Besoins transversaux en matière d'apprentissages"
* $terminologie-SERAFINPH#1.3.3.4 "Besoins pour la vie familiale, la parentalité, la vie affective et sexuelle"
* $terminologie-SERAFINPH#1.3.3.5 "Besoins pour apprendre à être pair-aidant"
* $terminologie-SERAFINPH#1.3.4 "Besoins pour participer à la vie sociale et se déplacer avec un moyen de transport"
* $terminologie-SERAFINPH#1.3.4.1 "Besoins pour participer à la vie sociale"
* $terminologie-SERAFINPH#1.3.4.2 "Besoins pour se déplacer avec un moyen de transport"
* $terminologie-SERAFINPH#1.3.5 "Besoins en matière de ressources et d'autosuffisance économique"
* $terminologie-SERAFINPH#1.3.5.1 "Besoins en matière de ressources et d'autosuffisance économique"