Alias: $terminologie-SERAFINPH = https://smt.esante.gouv.fr/terminologie-SERAFINPH

ValueSet: JDV_J283_PrestationsIndirects_SERAFIN
Id: JDV-J283-PrestationsIndirects-SERAFIN
Description: "Liste des prestations indirects provenant de la terminologie SERAFIN"
* ^meta.versionId = "3"
* ^meta.lastUpdated = "2024-10-31T18:01:43.422+00:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2024-10-25T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J283-PrestationsIndirects_SERAFIN/FHIR/JDV-J283-PrestationsIndirects-SERAFIN"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.252"
* ^version = "20241025120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-10-25T12:00:00+01:00"
* ^publisher = "ANS"
* ^contact.name = "ANS"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://esante.gouv.fr"
* ^jurisdiction = urn:iso:std:iso:3166#FR "France"
* $terminologie-SERAFINPH#3 "Prestations indirectes - Pilotage et fonctions supports"
* $terminologie-SERAFINPH#3.1 "Fonctions Gérer, manager, coopérer"
* $terminologie-SERAFINPH#3.1.1 "Gestion des ressources humaines"
* $terminologie-SERAFINPH#3.1.1.1 "Pilotage et direction"
* $terminologie-SERAFINPH#3.1.1.2 "Gestion des ressources humaines, de la Gestion previsionnelle des emplois et des competences et du dialogue socIal"
* $terminologie-SERAFINPH#3.1.2 "Gestion administrative, budgétaire, financière et comptable"
* $terminologie-SERAFINPH#3.1.2.1 "Gestion budgétaire, financière et comptable"
* $terminologie-SERAFINPH#3.1.2.2 "Gestion administrative"
* $terminologie-SERAFINPH#3.1.3 "Information et communication"
* $terminologie-SERAFINPH#3.1.3.1 "Communication (interne et externe), statistiques, rapport annuel et documents collectifs 2002-2"
* $terminologie-SERAFINPH#3.1.3.2 "Gestion des données des personnes accueillies, système d'information, informatique, TIC, archivage informatique des données, GED"
* $terminologie-SERAFINPH#3.1.4 "Qualité et sécurité"
* $terminologie-SERAFINPH#3.1.4.1 "Démarche d'amélioration continue de la qualité"
* $terminologie-SERAFINPH#3.1.4.2 "Analyse des pratiques, espaces ressource et soutien aux personnels"
* $terminologie-SERAFINPH#3.1.4.3 "Prestations de supervision"
* $terminologie-SERAFINPH#3.1.5 "Relations avec le territoire"
* $terminologie-SERAFINPH#3.1.5.1 "Coopérations, conventions avec les acteurs spécialisés et du droit commun"
* $terminologie-SERAFINPH#3.1.5.2 "Appui-Ressources et partenariats institutionnels"
* $terminologie-SERAFINPH#3.1.6 "Transports liés à gérer, manager, coopérer"
* $terminologie-SERAFINPH#3.2 "Fonctions logistiques"
* $terminologie-SERAFINPH#3.2.1 "Locaux et autres ressources pour accueillir"
* $terminologie-SERAFINPH#3.2.1.1 "Locaux et autres ressources pour héberger"
* $terminologie-SERAFINPH#3.2.1.2 "Locaux et autres ressources pour accueillir le jour"
* $terminologie-SERAFINPH#3.2.1.3 "Locaux et autres ressources pour réaliser des prestations de soins, de maintien et de développement des capacités fonctionnelles"
* $terminologie-SERAFINPH#3.2.1.4 "Locaux et autres ressources pour gérer, manager, coopérer"
* $terminologie-SERAFINPH#3.2.1.5 "Hygiène, entretien, sécurité des locaux, espaces extérieurs"
* $terminologie-SERAFINPH#3.2.2 "Fournir des repas"
* $terminologie-SERAFINPH#3.2.2.1 "Fournir des repas"
* $terminologie-SERAFINPH#3.2.3 "Entretenir le linge"
* $terminologie-SERAFINPH#3.2.3.1 "Entretenir le linge"
* $terminologie-SERAFINPH#3.2.4 "Transports liés au projet individuel"
* $terminologie-SERAFINPH#3.2.4.1 "Transports liés à accueillir (domicile-structure)"
* $terminologie-SERAFINPH#3.2.4.2 "Transports liés aux prestations de soins, de maintien et de developpement des capacités fonctionnelles"
* $terminologie-SERAFINPH#3.2.4.3 "Transports liés à l'autonomie et la participation sociale"
* $terminologie-SERAFINPH#3.2.5 "Transports des biens et matériels liés à la restauration et à l'entretien du linge"