Alias: $terminologie-SERAFINPH = https://smt.esante.gouv.fr/terminologie-SERAFINPH

ValueSet: JDV_J284_PrestationsDirects_SERAFIN
Id: JDV-J284-PrestationsDirects-SERAFIN
Description: "Liste des prestations directs provenant de la terminologie SERAFIN"
* ^meta.versionId = "3"
* ^meta.lastUpdated = "2024-10-31T18:01:43.931+00:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2024-10-25T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J284-PrestationsDirects_SERAFIN/FHIR/JDV-J284-PrestationsDirects-SERAFIN"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.253"
* ^version = "20241025120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-10-25T12:00:00+01:00"
* ^publisher = "ANS"
* ^contact.name = "ANS"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://esante.gouv.fr"
* ^jurisdiction = urn:iso:std:iso:3166#FR "France"
* $terminologie-SERAFINPH#2 "Prestations directes - Soins et d'accompagnement"
* $terminologie-SERAFINPH#2.1 "Prestations de soins, de maintien et de développement des capacités fonctionnelles"
* $terminologie-SERAFINPH#2.1.1 "Soins somatiques et psychiques"
* $terminologie-SERAFINPH#2.1.1.1 "Soins médicaux à visée préventive, curative et palliative"
* $terminologie-SERAFINPH#2.1.1.2 "Soins techniques et de surveillance infirmiers ou délégués"
* $terminologie-SERAFINPH#2.1.1.3 "Prestations des psychologues"
* $terminologie-SERAFINPH#2.1.1.4 "Prestations des pharmaciens et préparateurs en pharmacie"
* $terminologie-SERAFINPH#2.1.2 "Rééducation et réadaptation fonctionnelle"
* $terminologie-SERAFINPH#2.1.2.1 "Prestations des auxiliaires médicaux, des instructeurs en locomotion et avéjistes"
* $terminologie-SERAFINPH#2.2 "Prestations en matière d'autonomie"
* $terminologie-SERAFINPH#2.2.1 "Accompagnements pour les actes de la vie quotidienne"
* $terminologie-SERAFINPH#2.2.2 "Accompagnements pour la communication et les relations avec autrui"
* $terminologie-SERAFINPH#2.2.3 "Accompagnements pour prendre des décisions adaptées et pour la sécurité"
* $terminologie-SERAFINPH#2.3 "Prestations pour la participation sociale"
* $terminologie-SERAFINPH#2.3.1 "Accompagnements pour exercer ses droits"
* $terminologie-SERAFINPH#2.3.1.1 "Accompagnements à l'expression du projet personnalisé"
* $terminologie-SERAFINPH#2.3.1.2 "Accompagnements à l'exercice des droits et libertés"
* $terminologie-SERAFINPH#2.3.2 "Accompagnements au logement"
* $terminologie-SERAFINPH#2.3.2.1 "Accompagnements pour vivre dans un logement"
* $terminologie-SERAFINPH#2.3.2.2 "Accompagnements pour accomplir les activités domestiques"
* $terminologie-SERAFINPH#2.3.3 "Accompagnements pour exercer ses rôles sociaux"
* $terminologie-SERAFINPH#2.3.3.1 "Accompagnements pour mener sa vie d'élève, d'étudiant ou d'apprenti"
* $terminologie-SERAFINPH#2.3.3.2 "Accompagnements pour préparer sa vie professionnelle"
* $terminologie-SERAFINPH#2.3.3.3 "Accompagnements pour mener sa vie professionnelle"
* $terminologie-SERAFINPH#2.3.3.4 "Accompagnements pour réaliser des activités de jour spécialisées"
* $terminologie-SERAFINPH#2.3.3.5 "Accompagnements de la vie familiale, de la parentalité, de la vie affective et sexuelle"
* $terminologie-SERAFINPH#2.3.3.6 "Accompagnements pour l'exercice de mandats électoraux, la représentation des pairs et la pair aidance"
* $terminologie-SERAFINPH#2.3.4 "Accompagnements pour participer à la vie sociale"
* $terminologie-SERAFINPH#2.3.4.1 "Accompagnements du lien avec les proches et le voisinage"
* $terminologie-SERAFINPH#2.3.4.2 "Accompagnements pour la participation aux activités sociales et de loisirs"
* $terminologie-SERAFINPH#2.3.4.3 "Accompagnements pour le développement de l'autonomie pour les déplacements"
* $terminologie-SERAFINPH#2.3.5 "Accompagnements en matière de ressources et d'autogestion"
* $terminologie-SERAFINPH#2.3.5.1 "Accompagnements pour l'ouverture des droits"
* $terminologie-SERAFINPH#2.3.5.2 "Accompagnements pour l'autonomie de la personne dans la gestion des ressources"
* $terminologie-SERAFINPH#2.3.5.3 "Informations, conseils et mise en oeuvre des mesures de protection des adultes"
* $terminologie-SERAFINPH#2.4 "Prestation de coordination renforcée pour la cohérence du parcours"
* $terminologie-SERAFINPH#2.4.1 "Prestation de coordination renforcée pour la cohérence du parcours"