ValueSet: JDV_J108_EnsembleFonction_RASS
Id: JDV-J108-EnsembleFonction-RASS
Description: "Ensemble des fonctions et rôles du RASS"
* ^meta.versionId = "9"
* ^meta.lastUpdated = "2024-12-19T18:02:31.904+00:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J108-EnsembleFonction-RASS/FHIR/JDV-J108-EnsembleFonction-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.176"
* ^version = "20241213120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-12-13T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* $TRE-R21-Fonction#FON-01 "Titulaire de cabinet"
* $TRE-R21-Fonction#FON-02 "Associé dans une société d'exercice (SEL ou SCP)"
* $TRE-R21-Fonction#FON-03 "Titulaire d'officine"
* $TRE-R21-Fonction#FON-04 "Remplaçant du titulaire d'officine"
* $TRE-R21-Fonction#FON-05 "Adjoint"
* $TRE-R21-Fonction#FON-07 "Gérant après incapacité ou décès"
* $TRE-R21-Fonction#FON-09 "Responsable d'établissement"
* $TRE-R21-Fonction#FON-15 "Directeur de laboratoire"
* $TRE-R21-Fonction#FON-16 "Directeur-adjoint de laboratoire"
* $TRE-R21-Fonction#FON-17 "Collaborateur"
* $TRE-R21-Fonction#FON-18 "Assistant"
* $TRE-R21-Fonction#FON-19 "Praticien Conseil"
* $TRE-R21-Fonction#FON-21 "Médecin scolaire"
* $TRE-R21-Fonction#FON-22 "Remplaçant, intérimaire, intermittent"
* $TRE-R21-Fonction#FON-23 "Gérant"
* $TRE-R21-Fonction#FON-24 "Médecin de santé publique"
* $TRE-R21-Fonction#FON-29 "Médecin du travail"
* $TRE-R21-Fonction#FON-32 "Régulateur libéral"
* $TRE-R21-Fonction#FON-33 "Salarié en poste fixe"
* $TRE-R21-Fonction#FON-36 "Délégué"
* $TRE-R21-Fonction#FON-37 "Gérant de PUI"
* $TRE-R21-Fonction#FON-39 "Exercice en PMI"
* $TRE-R21-Fonction#FON-40 "Biologiste responsable"
* $TRE-R21-Fonction#FON-41 "Biologiste médical"
* $TRE-R21-Fonction#FON-42 "Assistant collaborateur"
* $TRE-R21-Fonction#FON-43 "Cadre de santé"
* $TRE-R21-Fonction#FON-45 "Directeur des soins"
* $TRE-R21-Fonction#FON-46 "Enseignant salarié"
* $TRE-R21-Fonction#FON-47 "Etudiant remplaçant, adjoint"
* $TRE-R21-Fonction#FON-48 "Interne"
* $TRE-R21-Fonction#FON-49 "Pharmacien responsable BPDO"
* $TRE-R21-Fonction#FON-50 "Pharmacien adjoint BPDO"
* $TRE-R21-Fonction#FON-51 "Remplacement partiel"
* $TRE-R21-Fonction#FON-52 "Etudiant militaire"
* $TRE-R21-Fonction#FON-53 "Médecin assistant"
* $TRE-R21-Fonction#FON-54 "Permanence des soins ambulatoires hors cabinet"
* $TRE-R21-Fonction#FON-55 "Participation libérale aux missions de service public d'un ES"
* $TRE-R21-Fonction#FON-56 "Intervention libérale dans le cadre d'un GCS"
* $TRE-R21-Fonction#FON-57 "Docteur junior"
* $TRE-R21-Fonction#FON-58 "Activité en piscine ou bassin"
* $TRE-R21-Fonction#FON-59 "Gérant d'antenne"
* $TRE-R21-Fonction#FON-AU "Fonction non définie"
* $TRE-R96-AutreFonctionSanitaire#407 "Tatoueur"
* $TRE-R96-AutreFonctionSanitaire#408 "Perceur corporel"
* $TRE-R96-AutreFonctionSanitaire#409 "Maquilleur permanent"
* $TRE-R85-RolePriseCharge#300 "Assistant de service social (PAERPA)"
* $TRE-R85-RolePriseCharge#301 "Coordination territoriale d'appui (PAERPA)"
* $TRE-R85-RolePriseCharge#302 "Aide et accompagnement à domicile (PAERPA)"
* $TRE-R85-RolePriseCharge#303 "Avocat participant aux processus de soins sans consentement (eSSS)"
* $TRE-R85-RolePriseCharge#304 "Assistant de service social (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#305 "Psychologue (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#306 "Psychothérapeute (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE-R85-RolePriseCharge#308 "Pilote MAIA"
* $TRE-R85-RolePriseCharge#309 "Gestionnaire de cas MAIA"
* $TRE-R85-RolePriseCharge#310 "Equipe médico-sociale APA"
* $TRE-R85-RolePriseCharge#311 "Autre acteur mettant en oeuvre la méthode MAIA"
* $TRE-R85-RolePriseCharge#312 "Autre professionnel"
* $TRE-R85-RolePriseCharge#313 "Aide-soignant"
* $TRE-R85-RolePriseCharge#314 "Ambulancier"
* $TRE-R85-RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE-R85-RolePriseCharge#317 "Préparateur en pharmacie (officine)"
* $TRE-R85-RolePriseCharge#318 "Auxiliaire de vie sociale"
* $TRE-R85-RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE-R85-RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE-R85-RolePriseCharge#321 "Médiateur familial"
* $TRE-R85-RolePriseCharge#322 "Assistant familial"
* $TRE-R85-RolePriseCharge#323 "Aide médico-psychologique (AMP)"
* $TRE-R85-RolePriseCharge#324 "Moniteur éducateur"
* $TRE-R85-RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE-R85-RolePriseCharge#326 "Educateur spécialisé"
* $TRE-R85-RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE-R85-RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#329 "Conseiller en génétique"
* $TRE-R85-RolePriseCharge#330 "Coordonnateur de parcours"
* $TRE-R85-RolePriseCharge#331 "Secrétaire médicale"
* $TRE-R85-RolePriseCharge#332 "Assistant médical"
* $TRE-R85-RolePriseCharge#333 "Responsable de secteur"
* $TRE-R85-RolePriseCharge#334 "Biologiste médical ni médecin ni pharmacien"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#350 "Aide à domicile"
* $TRE-R85-RolePriseCharge#351 "Assistant(e) maternel(le)"