ValueSet: JdvJ402TypeDroitPrestationMs
Id: jdv-j402-type-droit-prestation-ms
Title: "Jdv J402 Type Droit Prestation Ms"
Description: "Type de droit et prestation caractérisant la décision d'orientation."
* ^meta.versionId = "1"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2026-05-05T12:00:00+01:00"
* ^url = "https://smt.esante.gouv.fr/fhir/ValueSet/jdv-j402-type-droit-prestation-ms"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.242"
* ^version = "20260505120000"
* ^status = #draft
* ^experimental = false
* ^date = "2026-05-05T12:00:00.000+00:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FR

* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#1.1 "AAH L.821-1"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#1.1 "AAH L.821-1"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#1.2 "AAH L.821-2"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#2.1 "ACFP (Allocation compensatrice pour frais professionnels)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#2.2 "ACTP (Allocation compensatrice pour tierce personne)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#4.1 "Carte mobilité inclusion, Mention stationnement"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#4.2 "Carte mobilité inclusion, Mention invalidité"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#4.3 "Carte mobilité inclusion, Mention priorité"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.1 "PCH - élément 1 - Aide humaine"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.9 "PCH 1 - Aide humaine à la parentalité"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.2 "PCH - élément 2 - Aides techniques"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.10 "PCH 2 - Aides techniques à la parentalité"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.3 "PCH - élément 3 - Aménagement du logement"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.4 "PCH - élément 3 - Aménagement du véhicule"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.5 "PCH - élément 3 - Surcoûts liés au transport"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.6 "PCH - élément 4 - Charges spécifiques"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.7 "PCH - élément 4 - Charges exceptionnelles"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#5.8 "PCH - élément 5 - Aide animalière"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#6.1 "AEEH de base"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#6.2 "Complément 1 de l'AEEH"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#6.3 "Complément 2 de l'AEEH"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#6.4 "Complément 3 de l'AEEH"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#6.5 "Complément 4 de l'AEEH"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#6.6 "Complément 5 de l'AEEH"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#6.7 "Complément 6 de l'AEEH"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.1 "Orientation vers un Institut médico-éducatif (IME)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.2 "Orientation vers un Institut d'éducation motrice (IEM)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.3 "Orientation vers un institut pour personnes avec une déficience auditive"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.4 "Orientation vers un institut pour personnes avec une déficience visuelle"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.5 "Orientation vers un établissement pour enfants ou adolescents polyhandicapés"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.6 "Orientation vers un Institut thérapeutique, éducatif et pédagogique (ITEP)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.7 "Orientation vers le dispositif ITEP"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.8 "Orientation vers un Service d'éducation spéciale et de soins à domicile (SESSAD)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.9 "Orientation vers un Service d'accompagnement familial et d'éducation précoce (SAFEP)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.10 "Orientation vers un Service de soutien à l'éducation familiale et à la scolarisation (SSEFS)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.11 "Orientation vers un Service d'aide à l'acquisition de l'autonomie et à la scolarisation (SAAAS)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.12 "Orientation vers Service de soins et d'aide à domicile (SSAD)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.13 "Orientation vers un Institut d'éducation sensorielle (IES)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#7.99 "Orientation vers un autre établissement ou service médico-social Enfants"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.1 "Orientation en enseignement ordinaire"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.2 "Redoublement en maternelle"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.3 "Orientation en Enseignement adapté (SEGPA/EREA)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.4 "Orientation en Unité localisée pour l'inclusion scolaire (ULIS)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.6 "Orientation en Unité d'enseignement"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.7 "Orientation vers une Scolarisation en milieu ordinaire à temps partagé (UE et établissement scolaire)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.8 "Orientation vers une Unité d'enseignement et une scolarisation en ULIS à temps partagé"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.9 "Orientation vers un Pôle d'enseignement jeune sourd (PEJS)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.10 "Orientation vers une unité d'enseignement et une scolarisation en enseignement adapté à temps partagé"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#8.11 "Orientation vers un établissement d'autorégulation"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#10.1 "Accompagnant des élèves en situation de handicap (AESH) - aide individuelle"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#10.2 "Accompagnant des élèves en situation de handicap (AESH) - aide mutualisée"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#11.1 "Orientation en Etablissement ou service de réadaptation professionnelle (ESRP)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#11.2 "Orientation en Etablissement ou service de préorientation (ESPO)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#11.3 "Orientation vers l'unité d'évaluation, de réentrainement et d'orientation sociale et socioprofessionnelle pour personnes cérébro-lésées (UEROS)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#11.5 "Orientation en Etablissement et service d'accompagnement par le travail (ESAT)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#11.6 "Orientation vers une plateforme d'emploi accompagné"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#11.7 "Aide à l'insertion professionnelle - Subvention d'installation"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#13.1 "Orientation vers un Etablissement d'accueil non médicalisé"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#13.2 "Orientation vers un Etablissement d'accueil médicalisé en tout ou partie"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#13.3 "Orientation vers une Maison d'accueil spécialisée (MAS)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#13.4 "Orientation vers un Service d'accompagnement à la vie sociale (SAVS)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#13.5 "Orientation vers un Service d'accompagnement médico-social pour adultes handicapés (SAMSAH)"
* include https://smt.esante.gouv.fr/fhir/CodeSystem/tre-r420-droit-prestation#13.99 "Orientation vers un autre établissement ou service médico-social Adultes"
