ValueSet: JDV_J108_EnsembleFonction_RASS
Id: JDV-J108-EnsembleFonction-RASS
Description: "Ensemble des fonctions et rôles du RASS"
* ^meta.versionId = "10"
* ^meta.lastUpdated = "2025-03-31T17:32:56.483+00:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J108-EnsembleFonction-RASS/FHIR/JDV-J108-EnsembleFonction-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.176"
* ^version = "20250626120000"
* ^status = #active
* ^experimental = false
* ^date = "2025-06-26T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* $TRE_R21_Fonction#FON-01 "Titulaire de cabinet"
* $TRE_R21_Fonction#FON-02 "Associé dans une société d'exercice (SEL ou SCP)"
* $TRE_R21_Fonction#FON-03 "Titulaire d'officine"
* $TRE_R21_Fonction#FON-04 "Remplaçant du titulaire d'officine"
* $TRE_R21_Fonction#FON-05 "Adjoint"
* $TRE_R21_Fonction#FON-07 "Gérant après incapacité ou décès"
* $TRE_R21_Fonction#FON-09 "Responsable d'établissement"
* $TRE_R21_Fonction#FON-15 "Directeur de laboratoire"
* $TRE_R21_Fonction#FON-16 "Directeur-adjoint de laboratoire"
* $TRE_R21_Fonction#FON-17 "Collaborateur"
* $TRE_R21_Fonction#FON-18 "Assistant"
* $TRE_R21_Fonction#FON-19 "Praticien Conseil"
* $TRE_R21_Fonction#FON-21 "Médecin scolaire"
* $TRE_R21_Fonction#FON-22 "Remplaçant, intérimaire, intermittent"
* $TRE_R21_Fonction#FON-23 "Gérant"
* $TRE_R21_Fonction#FON-24 "Médecin de santé publique"
* $TRE_R21_Fonction#FON-29 "Médecin du travail"
* $TRE_R21_Fonction#FON-32 "Régulateur libéral"
* $TRE_R21_Fonction#FON-33 "Salarié en poste fixe"
* $TRE_R21_Fonction#FON-36 "Délégué"
* $TRE_R21_Fonction#FON-37 "Gérant de PUI"
* $TRE_R21_Fonction#FON-39 "Exercice en PMI"
* $TRE_R21_Fonction#FON-40 "Biologiste responsable"
* $TRE_R21_Fonction#FON-41 "Biologiste médical"
* $TRE_R21_Fonction#FON-42 "Assistant collaborateur"
* $TRE_R21_Fonction#FON-43 "Cadre de santé"
* $TRE_R21_Fonction#FON-45 "Directeur des soins"
* $TRE_R21_Fonction#FON-46 "Enseignant salarié"
* $TRE_R21_Fonction#FON-47 "Etudiant remplaçant, adjoint"
* $TRE_R21_Fonction#FON-48 "Interne"
* $TRE_R21_Fonction#FON-49 "Pharmacien responsable BPDO"
* $TRE_R21_Fonction#FON-50 "Pharmacien adjoint BPDO"
* $TRE_R21_Fonction#FON-51 "Remplacement partiel"
* $TRE_R21_Fonction#FON-52 "Etudiant militaire"
* $TRE_R21_Fonction#FON-54 "Permanence des soins ambulatoires hors cabinet"
* $TRE_R21_Fonction#FON-55 "Participation libérale aux missions de service public d'un ES"
* $TRE_R21_Fonction#FON-56 "Intervention libérale dans le cadre d'un GCS"
* $TRE_R21_Fonction#FON-57 "Docteur junior"
* $TRE_R21_Fonction#FON-58 "Activité en piscine ou bassin"
* $TRE_R21_Fonction#FON-59 "Gérant d'antenne"
* $TRE_R21_Fonction#FON-60 "Pharmacien remplaçant BPDO"
* $TRE_R21_Fonction#FON-AU "Fonction non définie"
* $TRE_R96_AutreFonctionSanitaire#407 "Tatoueur"
* $TRE_R96_AutreFonctionSanitaire#408 "Perceur corporel"
* $TRE_R96_AutreFonctionSanitaire#409 "Maquilleur permanent"
* $TRE_R85_RolePriseCharge#300 "Assistant de service social (PAERPA)"
* $TRE_R85_RolePriseCharge#301 "Coordination territoriale d'appui (PAERPA)"
* $TRE_R85_RolePriseCharge#302 "Aide et accompagnement à domicile (PAERPA)"
* $TRE_R85_RolePriseCharge#303 "Avocat participant aux processus de soins sans consentement (eSSS)"
* $TRE_R85_RolePriseCharge#304 "Assistant de service social (Expérimentation MAIA)"
* $TRE_R85_RolePriseCharge#305 "Psychologue (Expérimentation MAIA)"
* $TRE_R85_RolePriseCharge#306 "Psychothérapeute (Expérimentation MAIA)"
* $TRE_R85_RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE_R85_RolePriseCharge#308 "Pilote MAIA"
* $TRE_R85_RolePriseCharge#309 "Gestionnaire de cas MAIA"
* $TRE_R85_RolePriseCharge#310 "Equipe médico-sociale APA"
* $TRE_R85_RolePriseCharge#311 "Autre acteur mettant en oeuvre la méthode MAIA"
* $TRE_R85_RolePriseCharge#312 "Autre professionnel"
* $TRE_R85_RolePriseCharge#313 "Aide-soignant"
* $TRE_R85_RolePriseCharge#314 "Ambulancier"
* $TRE_R85_RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE_R85_RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE_R85_RolePriseCharge#317 "Préparateur en pharmacie (officine)"
* $TRE_R85_RolePriseCharge#318 "Auxiliaire de vie sociale"
* $TRE_R85_RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE_R85_RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE_R85_RolePriseCharge#321 "Médiateur familial"
* $TRE_R85_RolePriseCharge#322 "Assistant familial"
* $TRE_R85_RolePriseCharge#323 "Aide médico-psychologique (AMP)"
* $TRE_R85_RolePriseCharge#324 "Moniteur éducateur"
* $TRE_R85_RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE_R85_RolePriseCharge#326 "Educateur spécialisé"
* $TRE_R85_RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE_R85_RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE_R85_RolePriseCharge#329 "Conseiller en génétique"
* $TRE_R85_RolePriseCharge#330 "Coordonnateur de parcours"
* $TRE_R85_RolePriseCharge#331 "Secrétaire assistante médico-administrative"
* $TRE_R85_RolePriseCharge#332 "Assistant médical"
* $TRE_R85_RolePriseCharge#333 "Responsable de secteur"
* $TRE_R85_RolePriseCharge#334 "Biologiste médical ni médecin ni pharmacien"
* $TRE_R85_RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE_R85_RolePriseCharge#336 "Autre professionnel intervenant dans l'accueil et l'orientation des personnes"
* $TRE_R85_RolePriseCharge#337 "Autre professionnel intervenant dans la logistique"
* $TRE_R85_RolePriseCharge#338 "Autre professionnel intervenant dans l'hôtellerie et la restauration"
* $TRE_R85_RolePriseCharge#339 "Autre professionnel intervenant dans la direction de la qualité, hygiène, sécurité et environnement"
* $TRE_R85_RolePriseCharge#340 "Autre professionnel intervenant dans la direction des systèmes d'information"
* $TRE_R85_RolePriseCharge#341 "Autre professionnel intervenant dans la direction des finances et comptabilité"
* $TRE_R85_RolePriseCharge#342 "Autre professionnel intervenant dans la direction de la communication"
* $TRE_R85_RolePriseCharge#343 "Autre professionnel intervenant dans la direction des ressources humaines"
* $TRE_R85_RolePriseCharge#344 "Autre professionnel intervenant dans la direction des affaires médicales"
* $TRE_R85_RolePriseCharge#345 "Autre professionnel intervenant dans le social, éducatif, psychologie et culturel"
* $TRE_R85_RolePriseCharge#346 "Etudiant - infirmier"
* $TRE_R85_RolePriseCharge#347 "Etudiant - aide-soignant"
* $TRE_R85_RolePriseCharge#348 "Etudiant - auxiliaire de puériculture"
* $TRE_R85_RolePriseCharge#349 "Etudiant - masseur-kinésithérapeute"
* $TRE_R85_RolePriseCharge#350 "Aide à domicile"
* $TRE_R85_RolePriseCharge#351 "Assistant(e) maternel(le)"
* $TRE_R85_RolePriseCharge#353 "Membre de l'équipe de soins"
* $TRE_R85_RolePriseCharge#354 "Externe en médecine"
* $TRE_R85_RolePriseCharge#355 "Externe en odontologie"
* $TRE_R85_RolePriseCharge#356 "Externe en maïeutique"
* $TRE_R85_RolePriseCharge#357 "Externe en pharmacie"
* $TRE_R85_RolePriseCharge#358 "Autre étudiant"
* $TRE_R85_RolePriseCharge#359 "Directeur d'établissement"
* $TRE_R85_RolePriseCharge#360 "Brancardier"
* $TRE_R85_RolePriseCharge#361 "Educateur en activité physique adaptée"
* $TRE_R85_RolePriseCharge#362 "Technicien d'informations médicales"
* $TRE_R85_RolePriseCharge#363 "Attaché de recherche clinique"
* $TRE_R85_RolePriseCharge#364 "Praticien A Diplôme Hors Union Européenne (PADHUE)"
* $TRE_R85_RolePriseCharge#365 "Gestionnaire admissions / frais de séjour / traitement externe"
* $TRE_R85_RolePriseCharge#366 "Archiviste"
* $TRE_R85_RolePriseCharge#367 "Surveillant de nuit"
* $TRE_R85_RolePriseCharge#368 "Animateur"
* $TRE_R85_RolePriseCharge#369 "Biologiste médical non-médecin"
* $TRE_R85_RolePriseCharge#370 "Opérateur de Soins Non Programmés"